#!/usr/bin/env python3
"""
Critical L3 rate audit for smooth Gaussian double-curl benchmark fields.

Purpose:
- verify the exact parity cancellation of the pressure correlation for one symmetric seed;
- show numerically, with a deterministic spectral whole-space approximation, that an
  asymmetric two-seed superposition can make the pressure correlation positive or negative;
- test the exact amplitude homogeneities of the L3 balance terms.

The spectral box is a numerical quadrature/inversion device, not a physical periodic
container and not a Navier-Stokes time solver. Results involving the asymmetric pressure
correlation are COMPUTATIONAL CHECKS, not general theorems.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import numpy as np
import sympy as sp


def symbolic_single_seed_parity() -> dict:
    x, y, z = sp.symbols("x y z", real=True)
    coords = (x, y, z)
    r2 = x*x+y*y+z*z
    g = sp.exp(-r2)
    u = sp.Matrix([
        4*x*z*g,
        4*y*z*g,
        4*(1-x*x-y*y)*g,
    ])
    G = sp.Matrix([[sp.diff(u[i], coords[j]) for j in range(3)] for i in range(3)])
    adv = sp.Matrix([
        sp.simplify(sum(u[j]*G[i,j] for j in range(3)))
        for i in range(3)
    ])
    numerator = sp.factor((u.T*adv)[0])
    mag2 = sp.factor((u.T*u)[0])
    Q = sp.factor(sum(G[i,j]*G[j,i] for i in range(3) for j in range(3)))

    def refl(expr):
        return sp.simplify(expr.subs(z, -z))

    return {
        "Q_even_in_z": sp.simplify(refl(Q)-Q) == 0,
        "speed_squared_even_in_z": sp.simplify(refl(mag2)-mag2) == 0,
        "u_dot_adv_odd_in_z": sp.simplify(refl(numerator)+numerator) == 0,
        "Q": str(Q),
        "u_dot_adv": str(numerator),
        "consequence": (
            "The decaying whole-space pressure generated by even Q is even in z; "
            "u·∇|u|=(u·(u·∇)u)/|u| is odd. Hence Pi_3=∫p u·∇|u| dx=0 exactly "
            "for the single symmetric benchmark."
        ),
    }


def seed_field_grid(X, Y, Z, axis=2, center=(0.0,0.0,0.0), amplitude=1.0):
    ys = [X-center[0], Y-center[1], Z-center[2]]
    rr = ys[0]**2 + ys[1]**2 + ys[2]**2
    g = np.exp(-rr)
    u = np.empty((3,) + X.shape, dtype=float)
    for j in range(3):
        if j == axis:
            transverse = sum(ys[k]**2 for k in range(3) if k != axis)
            u[j] = amplitude*4.0*(1.0-transverse)*g
        else:
            u[j] = amplitude*4.0*ys[j]*ys[axis]*g
    return u


def spectral_diagnostics(specs, N=80, L=6.0):
    """Approximate whole-space diagnostics on a large decay window using FFT derivatives.

    specs: list of (axis, center_tuple, amplitude)
    """
    x = np.linspace(-L, L, N, endpoint=False)
    h = 2.0*L/N
    X,Y,Z = np.meshgrid(x,x,x,indexing="ij")
    u = np.zeros((3,N,N,N), dtype=float)
    for axis, center, amplitude in specs:
        u += seed_field_grid(X,Y,Z,axis=axis,center=center,amplitude=amplitude)

    k = 2.0*np.pi*np.fft.fftfreq(N,d=h)
    K = np.meshgrid(k,k,k,indexing="ij")
    grads = np.empty((3,3,N,N,N), dtype=float)
    for i in range(3):
        uh = np.fft.fftn(u[i])
        for j in range(3):
            grads[i,j] = np.fft.ifftn(1j*K[j]*uh).real

    divergence = sum(grads[i,i] for i in range(3))
    Q = np.einsum("ij...,ji...->...", grads, grads)

    qhat = np.fft.fftn(Q)
    k2 = K[0]**2+K[1]**2+K[2]**2
    phat = np.zeros_like(qhat)
    nz = k2 > 0
    phat[nz] = qhat[nz]/k2[nz]
    # pressure constant is irrelevant because integral of u·grad|u| vanishes for decaying divergence-free data
    p = np.fft.ifftn(phat).real

    adv = np.einsum("j...,ij...->i...", u, grads)
    speed = np.linalg.norm(u,axis=0)
    u_dot_adv = np.sum(u*adv,axis=0)
    u_dot_grad_speed = np.divide(
        u_dot_adv, speed,
        out=np.zeros_like(speed),
        where=speed > 1e-14,
    )

    grad_norm2 = np.sum(grads*grads,axis=(0,1))
    directional = np.zeros_like(speed)
    for j in range(3):
        dot = np.sum(u*grads[:,j],axis=0)
        directional += dot*dot
    d3_density = speed*grad_norm2 + np.divide(
        directional, speed,
        out=np.zeros_like(speed),
        where=speed > 1e-14,
    )

    dv = h**3
    return {
        "N": N,
        "L": L,
        "h": h,
        "T3": float(np.sum(speed**3)*dv),
        "Pi3": float(np.sum(p*u_dot_grad_speed)*dv),
        "D3": float(np.sum(d3_density)*dv),
        "divergence_max_abs": float(np.max(np.abs(divergence))),
        "boundary_speed_max": float(max(
            np.max(speed[0,:,:]), np.max(speed[-1,:,:]),
            np.max(speed[:,0,:]), np.max(speed[:,-1,:]),
            np.max(speed[:,:,0]), np.max(speed[:,:,-1]),
        )),
    }


def convergence_table(specs):
    return [spectral_diagnostics(specs,N=N,L=6.0) for N in (48,64,80,96)]


def run_checks():
    parity = symbolic_single_seed_parity()
    single = [(2,(0.0,0.0,0.0),1.0)]

    # Reflection-related asymmetric pairs: pressure correlations have opposite signs.
    positive_shape = [
        (2,(0.0,0.0,0.0),1.0),
        (0,(-1.0,0.0,0.0),1.0),
    ]
    negative_shape = [
        (2,(0.0,0.0,0.0),1.0),
        (0,(1.0,0.0,0.0),1.0),
    ]

    single_hi = spectral_diagnostics(single,N=80,L=6.0)
    pos_conv = convergence_table(positive_shape)
    neg_hi = spectral_diagnostics(negative_shape,N=80,L=6.0)
    pos = pos_conv[-1]

    # Exact amplitude homogeneities for a fixed spatial shape:
    # T3(Au)=A^3 T3, D3(Au)=A^3 D3, Pi3(Au)=A^4 Pi3 for A>0.
    nu = 1.0
    threshold = nu*pos["D3"]/pos["Pi3"]
    A_test = 120.0
    rate_at_test = 3.0*(A_test**4*pos["Pi3"] - nu*A_test**3*pos["D3"])

    pi_values = [row["Pi3"] for row in pos_conv]
    stable_positive = min(pi_values) > 0.0
    rel_spread = (max(pi_values)-min(pi_values))/max(abs(np.mean(pi_values)),1e-30)

    checks = {
        "single_Q_even": parity["Q_even_in_z"],
        "single_speed_even": parity["speed_squared_even_in_z"],
        "single_u_dot_adv_odd": parity["u_dot_adv_odd_in_z"],
        "single_numeric_Pi3_near_zero": abs(single_hi["Pi3"]) < 1e-8,
        "asymmetric_positive_Pi3_all_resolutions": stable_positive,
        "asymmetric_Pi3_resolution_spread_small": rel_spread < 0.01,
        "reflection_related_negative_Pi3": neg_hi["Pi3"] < 0.0,
        "opposite_sign_magnitudes_close": abs(pos["Pi3"]+neg_hi["Pi3"])/abs(pos["Pi3"]) < 0.01,
        "amplitude_threshold_finite": math.isfinite(threshold) and threshold > 0.0,
        "amplified_initial_L3_rate_positive_candidate": rate_at_test > 0.0,
    }

    return {
        "status": "COMPUTATIONAL CHECK + DERIVED SYMMETRY / CRITICAL-L3 RATE",
        "checks": checks,
        "passed": sum(bool(v) for v in checks.values()),
        "total": len(checks),
        "single_seed": {
            "parity": parity,
            "numerical": single_hi,
            "Pi3_exact_by_symmetry": 0.0,
        },
        "positive_pressure_shape": {
            "specification": "z-seed at 0 plus x-seed at (-1,0,0), equal amplitudes",
            "resolution_convergence": pos_conv,
            "representative": pos,
            "Pi3_relative_spread_48_to_96": rel_spread,
        },
        "negative_pressure_shape": {
            "specification": "z-seed at 0 plus x-seed at (1,0,0), equal amplitudes",
            "representative": neg_hi,
        },
        "amplitude_homogeneity": {
            "T3": "A^3",
            "D3": "A^3",
            "Pi3": "A^4",
            "nu": nu,
            "computational_threshold_A_for_positive_initial_rate": threshold,
            "test_amplitude": A_test,
            "predicted_initial_dT3_dt_at_test_amplitude": rate_at_test,
        },
        "interpretation": {
            "single_seed": "The symmetric seed hides the pressure obstruction because Pi3 cancels exactly by reflection parity.",
            "asymmetric_seed": "Breaking that symmetry produces a sign-indefinite pressure correlation. Positive Pi3 is stable over the tested resolutions.",
            "route_status": "Naive monotone decay of the global L3 channel is a FAILED-ROUTE CANDIDATE supported computationally, not yet a rigorous counterexample theorem.",
            "next_target": "Control Pi3 without assuming the critical norm bound that the argument is trying to prove."
        },
        "numerical_boundary": (
            "Pressure is obtained by spectral inversion of -Delta on a large decay window. "
            "This approximates the whole-space Poisson solve; it is not a physical periodic-domain model. "
            "The asymmetric sign conclusion is reported only as a computational check."
        ),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--output-dir",default="results")
    args=ap.parse_args()
    out=Path(args.output_dir); out.mkdir(parents=True,exist_ok=True)
    d=run_checks()
    (out/"critical_l3_rate_baseline.json").write_text(json.dumps(d,indent=2),encoding="utf-8")
    pos=d["positive_pressure_shape"]["representative"]
    neg=d["negative_pressure_shape"]["representative"]
    amp=d["amplitude_homogeneity"]
    lines=[
        "# Critical L3 pressure-rate baseline","",
        f"Checks passed: **{d['passed']}/{d['total']}**","",
        "## Symmetric seed","",
        "Reflection parity gives `Pi3=0` exactly for the single z-axis Gaussian benchmark.",
        f"The spectral audit gives `Pi3≈{d['single_seed']['numerical']['Pi3']:.3e}`.","",
        "## Asymmetric superposition","",
        f"Positive-pressure shape: `Pi3≈{pos['Pi3']:.12g}`, `D3≈{pos['D3']:.12g}`, `T3≈{pos['T3']:.12g}`.",
        f"Reflection-related shape: `Pi3≈{neg['Pi3']:.12g}`.",
        f"Resolution spread in positive `Pi3`: `{d['positive_pressure_shape']['Pi3_relative_spread_48_to_96']:.3%}`.","",
        "Thus the pressure correlation is not sign-fixed in these deterministic benchmarks.","",
        "## Amplitude homogeneity","",
        "For a fixed shape and positive overall amplitude `A`, `T3` and `D3` scale as `A^3`, while `Pi3` scales as `A^4`.",
        f"For `nu=1`, the computed crossover is `A≈{amp['computational_threshold_A_for_positive_initial_rate']:.6g}`.",
        f"At `A={amp['test_amplitude']:.0f}`, the balance predicts `dT3/dt≈{amp['predicted_initial_dT3_dt_at_test_amplitude']:.12g}>0` at `t=0` for this numerical shape.","",
        "Status: **FAILED-ROUTE CANDIDATE / COMPUTATIONAL COUNTEREXAMPLE**, not a rigorous theorem that the exact whole-space solution has increasing L3 norm.","",
        "## Remaining obstruction","",
        "The DSD critical channel route still requires a non-circular estimate of the pressure correlation `Pi3`; simple monotonicity cannot be assumed.","",
        "## Numerical boundary","",
        d["numerical_boundary"],
    ]
    (out/"critical_l3_rate_baseline.md").write_text("\n".join(lines),encoding="utf-8")
    print(f"Critical L3 rate audit: {d['passed']}/{d['total']} checks passed")
    if d["passed"] != d["total"]:
        raise SystemExit(1)

if __name__ == "__main__":
    main()
